import re
import requests

# new api key

IAM_API_KEY = "bJgB6dLqbFuhvSyvTm2ih_re2XARbL735OoU8VR3xhjq"

PROJECT_ID = "4f6cff39-84dc-4893-bd77-d5dcaf664c5c"

MODEL_ID = "meta-llama/llama-3-3-70b-instruct"


# --------------------------------------------------


def get_access_token():

    url = "https://iam.cloud.ibm.com/identity/token"

    headers = {
        "Content-Type": "application/x-www-form-urlencoded"
    }

    data = {
        "grant_type": "urn:ibm:params:oauth:grant-type:apikey",
        "apikey": IAM_API_KEY
    }

    response = requests.post(
        url,
        headers=headers,
        data=data
    )

    response.raise_for_status()

    return response.json()["access_token"]


# --------------------------------------------------

SYSTEM_PROMPT = """
You convert recruiter requests into SQLite SQL.

Database:

ResumeUploaded(
id,
name,
email,
phone,
skills,
experience,
designation,
company,
education,
specialization,
university,
projects,
certifications,
languages,
uploaded_at
)

Rules:

Return ONLY one SQLite SELECT query.

Never explain.

Never return markdown.

Never return JSON.

Never return text before or after SQL.

Use LOWER(column) LIKE LOWER('%text%') for text search.

Use AND unless user explicitly says OR.

Use experience comparisons naturally.

Examples:

Python developer

SELECT *
FROM ResumeUploaded
WHERE LOWER(skills) LIKE LOWER('%python%');

Python and AWS

SELECT *
FROM ResumeUploaded
WHERE LOWER(skills) LIKE LOWER('%python%')
AND LOWER(skills) LIKE LOWER('%aws%');

Java OR Python

SELECT *
FROM ResumeUploaded
WHERE LOWER(skills) LIKE LOWER('%java%')
OR LOWER(skills) LIKE LOWER('%python%');

Software engineer

SELECT *
FROM ResumeUploaded
WHERE LOWER(designation) LIKE LOWER('%software engineer%');

Google employee

SELECT *
FROM ResumeUploaded
WHERE LOWER(company) LIKE LOWER('%google%');

BTech Computer Science

SELECT *
FROM ResumeUploaded
WHERE LOWER(education) LIKE LOWER('%btech%')
AND LOWER(specialization) LIKE LOWER('%computer science%');

Experience at least 3 years

SELECT *
FROM ResumeUploaded
WHERE experience >= 3;

Latest resumes

SELECT *
FROM ResumeUploaded
ORDER BY uploaded_at DESC;

Latest resumes

SELECT *
FROM ResumeUploaded
ORDER BY uploaded_at DESC;
"""


# --------------------------------------------------


def extract_sql(text):

    match = re.search(
        r"(SELECT\s.+?;)",
        text,
        re.IGNORECASE | re.DOTALL
    )

    if match:
        return match.group(1)

    match = re.search(
        r"(SELECT\s.+)",
        text,
        re.IGNORECASE | re.DOTALL
    )

    if match:
        return match.group(1).strip()

    return None


# --------------------------------------------------


def clean_sql(sql):

    sql = sql.replace("```sql", "")
    sql = sql.replace("```", "")
    sql = sql.strip()

    sql = sql.rstrip(".")

    if ";" not in sql:
        sql += ";"

    return sql


# --------------------------------------------------


def generate_sql(user_query):

    access_token = get_access_token()

    url = "https://us-south.ml.cloud.ibm.com/ml/v1/text/generation?version=2023-05-29"

    headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json",
        "Accept": "application/json"
    }

    prompt = f"""
{SYSTEM_PROMPT}

Recruiter Request:

{user_query}

SQL:
"""

    body = {

        "model_id": MODEL_ID,

        "project_id": PROJECT_ID,

        "input": prompt,

        "parameters": {
            "temperature": 0,
            "max_new_tokens": 120
        }
    }

    response = requests.post(
        url,
        headers=headers,
        json=body
    )

    print("=" * 60)
    print("IBM SQL API Status:", response.status_code)
    print("=" * 60)

    response.raise_for_status()

    result = response.json()

    generated = result["results"][0]["generated_text"]

    print(generated)

    sql = extract_sql(generated)

    if sql is None:
        raise Exception("IBM Watsonx could not generate a valid SQL query.")

    sql = clean_sql(sql)

    if not sql.lower().startswith("select"):
        raise Exception("Invalid SQL generated by IBM Watsonx.")

    print("\nGenerated SQL\n")
    print(sql)

    return sql